import Rate from '../models/rateModel.js';
import countries from 'world-countries';



// Seed full initial data
export const seedRates = async (req, res) => {
  try {
    
    

// const seedData = [
//   { weight: 0.050, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1140 },
//   { weight: 0.050, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1140 },
//   { weight: 0.100, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1180 },
//   { weight: 0.100, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1180 },
//   { weight: 0.150, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1220 },
//   { weight: 0.150, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1220 },
//   { weight: 0.200, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1240 },
//   { weight: 0.200, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1240 },
//   { weight: 0.250, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1280 },
//   { weight: 0.250, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1280 },
//   { weight: 0.300, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1320 },
//   { weight: 0.300, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1320 },
//   { weight: 0.350, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1350 },
//   { weight: 0.350, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1350 },
//   { weight: 0.400, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1380 },
//   { weight: 0.400, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1380 },
//   { weight: 0.450, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1480 },
//   { weight: 0.450, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1480 },
//   { weight: 0.500, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1590 },
//   { weight: 0.500, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1590 },
//   { weight: 0.600, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1650 },
//   { weight: 0.600, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1650 },
//   { weight: 0.700, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1700 },
//   { weight: 0.700, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1700 },
//   { weight: 0.800, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1760 },
//   { weight: 0.800, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1760 },
//   { weight: 0.900, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1810 },
//   { weight: 0.900, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1810 },
//   { weight: 1.000, dest_country: "Singapore", country_code: "SGP", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Austria", country_code: "AUT", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Belgium", country_code: "BEL", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Bulgaria", country_code: "BGR", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Croatia", country_code: "HRV", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Czech Republic", country_code: "CZE", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Denmark", country_code: "DNK", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Greece", country_code: "GRC", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Hungary", country_code: "HUN", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Ireland", country_code: "IRL", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Italy", country_code: "ITA", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Luxembourg", country_code: "LUX", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Netherlands", country_code: "NLD", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Poland", country_code: "POL", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Portugal", country_code: "PRT", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Romania", country_code: "ROU", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Slovakia", country_code: "SVK", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Slovenia", country_code: "SVN", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Spain", country_code: "ESP", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Sweden", country_code: "SWE", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "Germany", country_code: "DEU", package: "Direct", rate: 1870 },
//   { weight: 1.000, dest_country: "France", country_code: "FRA", package: "Direct", rate: 1870 },
// ];

// const seedData = [
//   { weight: 0.050, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1500 },
//   { weight: 0.050, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1500 },
//   { weight: 0.050, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1500 },
//   { weight: 0.050, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1500 },
//   { weight: 0.050, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1500 },

//   { weight: 0.100, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1600 },
//   { weight: 0.100, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1600 },
//   { weight: 0.100, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1600 },
//   { weight: 0.100, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1600 },
//   { weight: 0.100, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1600 },

//   { weight: 0.150, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1700 },
//   { weight: 0.150, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1700 },
//   { weight: 0.150, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1700 },
//   { weight: 0.150, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1700 },
//   { weight: 0.150, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1700 },

//   { weight: 0.200, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1750 },
//   { weight: 0.200, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1750 },
//   { weight: 0.200, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1750 },
//   { weight: 0.200, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1750 },
//   { weight: 0.200, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1750 },

//   { weight: 0.250, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1800 },
//   { weight: 0.250, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1800 },
//   { weight: 0.250, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1800 },
//   { weight: 0.250, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1800 },
//   { weight: 0.250, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1800 },

//   { weight: 0.300, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1850 },
//   { weight: 0.300, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1850 },
//   { weight: 0.300, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1850 },
//   { weight: 0.300, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1850 },
//   { weight: 0.300, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1850 },

//   { weight: 0.350, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1900 },
//   { weight: 0.350, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1900 },
//   { weight: 0.350, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1900 },
//   { weight: 0.350, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1900 },
//   { weight: 0.350, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1900 },

//   { weight: 0.400, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 1950 },
//   { weight: 0.400, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 1950 },
//   { weight: 0.400, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 1950 },
//   { weight: 0.400, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 1950 },
//   { weight: 0.400, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 1950 },

//   { weight: 0.450, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2000 },
//   { weight: 0.450, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2000 },
//   { weight: 0.450, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2000 },
//   { weight: 0.450, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2000 },
//   { weight: 0.450, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2000 },

//   { weight: 0.500, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2050 },
//   { weight: 0.500, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2050 },
//   { weight: 0.500, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2050 },
//   { weight: 0.500, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2050 },
//   { weight: 0.500, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2050 },

//   { weight: 0.600, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2100 },
//   { weight: 0.600, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2100 },
//   { weight: 0.600, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2100 },
//   { weight: 0.600, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2100 },
//   { weight: 0.600, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2100 },

//   { weight: 0.700, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2150 },
//   { weight: 0.700, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2150 },
//   { weight: 0.700, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2150 },
//   { weight: 0.700, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2150 },
//   { weight: 0.700, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2150 },

//   { weight: 0.800, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2200 },
//   { weight: 0.800, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2200 },
//   { weight: 0.800, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2200 },
//   { weight: 0.800, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2200 },
//   { weight: 0.800, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2200 },

//   { weight: 0.900, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2250 },
//   { weight: 0.900, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2250 },
//   { weight: 0.900, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2250 },
//   { weight: 0.900, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2250 },
//   { weight: 0.900, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2250 },

//   { weight: 1.000, dest_country: "Estonia", country_code: "EST", package: "Direct", rate: 2300 },
//   { weight: 1.000, dest_country: "Saudi Arabia", country_code: "SAU", package: "Direct", rate: 2300 },
//   { weight: 1.000, dest_country: "Finland", country_code: "FIN", package: "Direct", rate: 2300 },
//   { weight: 1.000, dest_country: "Latvia", country_code: "LVA", package: "Direct", rate: 2300 },
//   { weight: 1.000, dest_country: "Lithuania", country_code: "LTU", package: "Direct", rate: 2300 },
// ];

// const seedData = [
//   { weight: 0.050, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1170 },
//   { weight: 0.050, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1170 },

//   { weight: 0.100, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1210 },
//   { weight: 0.100, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1210 },

//   { weight: 0.150, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1250 },
//   { weight: 0.150, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1250 },

//   { weight: 0.200, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1270 },
//   { weight: 0.200, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1270 },

//   { weight: 0.250, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1310 },
//   { weight: 0.250, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1310 },

//   { weight: 0.300, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1350 },
//   { weight: 0.300, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1350 },

//   { weight: 0.350, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1380 },
//   { weight: 0.350, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1380 },

//   { weight: 0.400, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1410 },
//   { weight: 0.400, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1410 },

//   { weight: 0.450, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1510 },
//   { weight: 0.450, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1510 },

//   { weight: 0.500, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1620 },
//   { weight: 0.500, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1620 },

//   { weight: 0.600, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1680 },
//   { weight: 0.600, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1680 },

//   { weight: 0.700, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1730 },
//   { weight: 0.700, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1730 },

//   { weight: 0.800, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1790 },
//   { weight: 0.800, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1790 },

//   { weight: 0.900, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1840 },
//   { weight: 0.900, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1840 },

//   { weight: 1.000, dest_country: "Germany", country_code: "DEU", package: "Premium", rate: 1900 },
//   { weight: 1.000, dest_country: "France", country_code: "FRA", package: "Premium", rate: 1900 }
// ];

const seedData = [
  { weight: 0.050, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1500 },
  { weight: 0.050, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1500 },

  { weight: 0.100, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1600 },
  { weight: 0.100, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1600 },

  { weight: 0.150, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1700 },
  { weight: 0.150, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1700 },
    { weight: 0.200, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1750 },
  { weight: 0.200, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1750 },

  { weight: 0.250, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1800 },
  { weight: 0.250, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1800 },

  { weight: 0.300, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1850 },
  { weight: 0.300, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1850 },

  { weight: 0.350, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1900 },
  { weight: 0.350, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1900 },

  { weight: 0.400, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 1950 },
  { weight: 0.400, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 1950 },
    { weight: 0.450, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2000 },
  { weight: 0.450, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2000 },

  { weight: 0.500, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2050 },
  { weight: 0.500, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2050 },

  { weight: 0.600, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2100 },
  { weight: 0.600, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2100 },

  { weight: 0.700, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2150 },
  { weight: 0.700, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2150 },

  { weight: 0.800, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2200 },
  { weight: 0.800, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2200 },

  { weight: 0.900, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2250 },
  { weight: 0.900, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2250 },

  { weight: 1.000, dest_country: "Estonia", country_code: "EST", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Finland", country_code: "FIN", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "French Southern Territories", country_code: "ATF", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Iran", country_code: "IRN", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Latvia", country_code: "LVA", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Lithuania", country_code: "LTU", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Man", country_code: "IMN", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "New Zealand", country_code: "NZL", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Russia", country_code: "RUS", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Saint-Martin", country_code: "MAF", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Saudi Arabia", country_code: "SAU", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "South Sudan", country_code: "SSD", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Sri Lanka", country_code: "LKA", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Switzerland", country_code: "CHE", package: "Worldwide", rate: 2300 },
  { weight: 1.000, dest_country: "Ukraine", country_code: "UKR", package: "Worldwide", rate: 2300 }
];




    await Rate.insertMany(seedData);

    res.status(201).json({ message: 'All rates seeded successfully!' });
  } catch (error) {
    res.status(500).json({ message: 'Seeding failed', error: error.message });
  }
};

// Create a new rate
export const createRate = async (req, res) => {
  try {
    const { weight, dest_country, package: pkg, rate } = req.body;

    const newRate = await Rate.create({ weight, dest_country, package: pkg, rate });
    res.status(201).json(newRate);
  } catch (error) {
    res.status(400).json({ message: 'Error creating rate', error: error.message });
  }
};

// Get all rates
export const getAllRates = async (req, res) => {
  try {
    const rates = await Rate.find().sort({ dest_country: 1, weight: 1 });
    res.status(200).json(rates);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching rates', error: error.message });
  }
};

// Update a rate
export const updateRate = async (req, res) => {
  try {
    const { id } = req.params;
    const updatedRate = await Rate.findByIdAndUpdate(id, req.body, { new: true, runValidators: true });
    
    if (!updatedRate) {
      return res.status(404).json({ message: 'Rate not found' });
    }

    res.status(200).json(updatedRate);
  } catch (error) {
    res.status(400).json({ message: 'Error updating rate', error: error.message });
  }
};

// Delete a rate
export const deleteRate = async (req, res) => {
  try {
    const { id } = req.params;
    const deletedRate = await Rate.findByIdAndDelete(id);

    if (!deletedRate) {
      return res.status(404).json({ message: 'Rate not found' });
    }

    res.status(200).json({ message: 'Rate deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Error deleting rate', error: error.message });
  }
};

// controllers/countryController.js

export const getAllCountries = async (req, res) => {
  try {
    // Format countries for dropdown: { name: "India", code: "IND" }
    const formattedCountries = countries.map((country) => ({
      name: country.name.common,
      code: country.cca3, // Alpha-3 code like IND, USA, GBR
    }));

    // Sort alphabetically by name
    formattedCountries.sort((a, b) => a.name.localeCompare(b.name));

    res.status(200).json(formattedCountries);
  } catch (error) {
    res.status(500).json({
      message: "Error fetching countries",
      error: error.message,
    });
  }
};

