import Rate from '../models/rateModel.js';
import countries from 'world-countries';



// Seed full initial data
export const seedRates = async (req, res) => {
  try {
    
    //delete existing rates
    

  //   const seedData = [
    
  // {"weight": 0.050, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Singapore", "country_code": "SGP", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Australia", "country_code": "AUS", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Austria", "country_code": "AUT", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Belgium", "country_code": "BEL", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Bulgaria", "country_code": "BGR", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Croatia", "country_code": "HRV", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Czech Republic", "country_code": "CZE", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Denmark", "country_code": "DNK", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Greece", "country_code": "GRC", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Hungary", "country_code": "HUN", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Ireland", "country_code": "IRL", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Italy", "country_code": "ITA", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Luxembourg", "country_code": "LUX", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Netherlands", "country_code": "NLD", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Poland", "country_code": "POL", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Portugal", "country_code": "PRT", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Romania", "country_code": "ROU", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Slovakia", "country_code": "SVK", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Slovenia", "country_code": "SVN", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Spain", "country_code": "ESP", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Sweden", "country_code": "SWE", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "Germany", "country_code": "DEU", "package": "Direct", "rate": 1585},

  // {"weight": 0.050, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 966},
  // {"weight": 0.100, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1000},
  // {"weight": 0.150, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1034},
  // {"weight": 0.200, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1051},
  // {"weight": 0.250, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1085},
  // {"weight": 0.300, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1119},
  // {"weight": 0.350, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1144},
  // {"weight": 0.400, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1169},
  // {"weight": 0.450, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1254},
  // {"weight": 0.500, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1347},
  // {"weight": 0.600, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1398},
  // {"weight": 0.700, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1492},
  // {"weight": 0.900, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1534},
  // {"weight": 1.000, "dest_country": "France", "country_code": "FRA", "package": "Direct", "rate": 1585},
  
  // {"weight": 0.050, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Estonia", "country_code": "EST", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Finland", "country_code": "FIN", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "French Southern Territories", "country_code": "ATF", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Iran", "country_code": "IRN", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Latvia", "country_code": "LVA", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Lithuania", "country_code": "LTU", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Isle of Man", "country_code": "IMN", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "New Zealand", "country_code": "NZL", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Russia", "country_code": "RUS", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Saint Martin", "country_code": "MAF", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Saudi Arabia", "country_code": "SAU", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "South Sudan", "country_code": "SSD", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Sri Lanka", "country_code": "LKA", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Switzerland", "country_code": "CHE", "package": "Worldwide", "rate": 1949},

  // {"weight": 0.050, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1271},
  // {"weight": 0.100, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1356},
  // {"weight": 0.150, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1441},
  // {"weight": 0.200, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1483},
  // {"weight": 0.250, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1525},
  // {"weight": 0.300, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1568},
  // {"weight": 0.350, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1610},
  // {"weight": 0.400, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1653},
  // {"weight": 0.450, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1695},
  // {"weight": 0.500, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1737},
  // {"weight": 0.600, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1780},
  // {"weight": 0.700, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1822},
  // {"weight": 0.800, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1864},
  // {"weight": 0.900, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1907},
  // {"weight": 1.000, "dest_country": "Ukraine", "country_code": "UKR", "package": "Worldwide", "rate": 1949},

  
  // {"weight": 0.050, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 992},
  // {"weight": 0.100, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1025},
  // {"weight": 0.150, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1059},
  // {"weight": 0.200, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1076},
  // {"weight": 0.250, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1110},
  // {"weight": 0.300, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1144},
  // {"weight": 0.350, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1169},
  // {"weight": 0.400, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1195},
  // {"weight": 0.450, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1280},
  // {"weight": 0.500, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1373},
  // {"weight": 0.600, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1424},
  // {"weight": 0.700, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1466},
  // {"weight": 0.800, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1517},
  // {"weight": 0.900, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1559},
  // {"weight": 1.000, "dest_country": "Germany", "country_code": "DEU", "package": "Premium DPD", "rate": 1610},

  // {"weight": 0.050, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 992},
  // {"weight": 0.100, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1025},
  // {"weight": 0.150, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1059},
  // {"weight": 0.200, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1076},
  // {"weight": 0.250, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1110},
  // {"weight": 0.300, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1144},
  // {"weight": 0.350, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1169},
  // {"weight": 0.400, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1195},
  // {"weight": 0.450, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1280},
  // {"weight": 0.500, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1373},
  // {"weight": 0.600, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1424},
  // {"weight": 0.700, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1466},
  // {"weight": 0.800, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1517},
  // {"weight": 0.900, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1559},
  // {"weight": 1.000, "dest_country": "France", "country_code": "FRA", "package": "Premium DPD", "rate": 1610},


  // {"weight": 0.050, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 678},
  // {"weight": 0.100, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 763},
  // {"weight": 0.150, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 805},
  // {"weight": 0.200, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 847},
  // {"weight": 0.250, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 932},
  // {"weight": 0.300, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1017},
  // {"weight": 0.350, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1102},
  // {"weight": 0.400, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1186},
  // {"weight": 0.450, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1271},
  // {"weight": 0.500, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1356},
  // {"weight": 0.600, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1441},
  // {"weight": 0.700, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1525},
  // {"weight": 0.800, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1610},
  // {"weight": 0.900, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1695},
  // {"weight": 1.000, "dest_country": "United States", "country_code": "USA", "package": "Premium Self", "rate": 1780},

  // {"weight": 0.500, "dest_country": "United States", "country_code": "USA", "package": "Express", "rate": 2372.88},
  
  // {"weight": 0.050, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 593},
  // {"weight": 0.100, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 678},
  // {"weight": 0.150, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 720},
  // {"weight": 0.200, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 763},
  // {"weight": 0.250, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 847},
  // {"weight": 0.300, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 932},
  // {"weight": 0.350, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1017},
  // {"weight": 0.400, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1102},
  // {"weight": 0.450, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1186},
  // {"weight": 0.500, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1271},
  // {"weight": 0.600, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1356},
  // {"weight": 0.700, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1441},
  // {"weight": 0.800, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1525},
  // {"weight": 0.900, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1610},
  // {"weight": 1.000, "dest_country": "United States", "country_code": "USA", "package": "Direct", "rate": 1695},
  
  // {"weight": 0.050, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1000},
  // {"weight": 0.100, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1127},
  // {"weight": 0.150, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1186},
  // {"weight": 0.200, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1203},
  // {"weight": 0.250, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1237},
  // {"weight": 0.300, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1271},
  // {"weight": 0.350, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1297},
  // {"weight": 0.400, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1322},
  // {"weight": 0.450, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1407},
  // {"weight": 0.500, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1500},
  // {"weight": 0.600, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1551},
  // {"weight": 0.700, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1593},
  // {"weight": 0.800, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1644},
  // {"weight": 0.900, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1686},
  // {"weight": 1.000, "dest_country": "United States (Remote)", "country_code": "USA", "package": "Premium Self", "rate": 1737},

  // {"weight": 0.050, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 636},
  // {"weight": 0.100, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 712},
  // {"weight": 0.150, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 780},
  // {"weight": 0.200, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 847},
  // {"weight": 0.250, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 907},
  // {"weight": 0.300, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 966},
  // {"weight": 0.350, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1025},
  // {"weight": 0.400, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1085},
  // {"weight": 0.450, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1144},
  // {"weight": 0.500, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1212},
  // {"weight": 0.600, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1314},
  // {"weight": 0.700, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1415},
  // {"weight": 0.800, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1517},
  // {"weight": 0.900, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1619},
  // {"weight": 1.000, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Direct", "rate": 1720},
  // {"weight": 0.500, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Express", "rate": 2372.88},
  // {"weight": 0.050, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 966},
  // {"weight": 0.100, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1000},
  // {"weight": 0.150, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1034},
  // {"weight": 0.200, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1051},
  // {"weight": 0.250, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1085},
  // {"weight": 0.300, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1119},
  // {"weight": 0.350, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1144},
  // {"weight": 0.400, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1169},
  // {"weight": 0.450, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1254},
  // {"weight": 0.500, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1347},
  // {"weight": 0.600, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1398},
  // {"weight": 0.700, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1441},
  // {"weight": 0.800, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1492},
  // {"weight": 0.900, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1534},
  // {"weight": 1.000, "dest_country": "United Kingdom", "country_code": "GBR", "package": "Premium DPD", "rate": 1585}



  //   ]

  const seedData = [
    
  {"weight": 0.050, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 831},
  {"weight": 0.100, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 873},
  {"weight": 0.150, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1076},
  {"weight": 0.200, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1093},
  {"weight": 0.250, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1127},
  {"weight": 0.300, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1161},
  {"weight": 0.350, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1144},
  {"weight": 0.400, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1186},
  {"weight": 0.450, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1212},
  {"weight": 0.500, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1297},
  {"weight": 0.600, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1390},
  {"weight": 0.700, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1441},
  {"weight": 0.800, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1483},
  {"weight": 0.900, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1534},
  {"weight": 1.000, "dest_country": "Canada", "country_code": "CAN", "package": "Direct", "rate": 1627}

  ]



    await Rate.insertMany(seedData);

    res.status(201).json({ message: 'All rates seeded successfully!' });
  } catch (error) {
    res.status(500).json({ message: 'Seeding failed', error: error.message });
  }
};

// Create a new rate
export const createRate = async (req, res) => {
  try {
    const { weight, dest_country, package: pkg, rate } = req.body;

    const newRate = await Rate.create({ weight, dest_country, package: pkg, rate });
    res.status(201).json(newRate);
  } catch (error) {
    res.status(400).json({ message: 'Error creating rate', error: error.message });
  }
};

// Get all rates
export const getAllRates = async (req, res) => {
  try {
    const rates = await Rate.find().sort({ dest_country: 1, weight: 1 });
    res.status(200).json(rates);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching rates', error: error.message });
  }
};

// Update a rate
export const updateRate = async (req, res) => {
  try {
    const { id } = req.params;
    const updatedRate = await Rate.findByIdAndUpdate(id, req.body, { new: true, runValidators: true });
    
    if (!updatedRate) {
      return res.status(404).json({ message: 'Rate not found' });
    }

    res.status(200).json(updatedRate);
  } catch (error) {
    res.status(400).json({ message: 'Error updating rate', error: error.message });
  }
};

// Delete a rate
export const deleteRate = async (req, res) => {
  try {
    const { id } = req.params;
    const deletedRate = await Rate.findByIdAndDelete(id);

    if (!deletedRate) {
      return res.status(404).json({ message: 'Rate not found' });
    }

    res.status(200).json({ message: 'Rate deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Error deleting rate', error: error.message });
  }
};

// controllers/countryController.js

export const getAllCountries = async (req, res) => {
  try {
    // Format countries for dropdown: { name: "India", code: "IND" }
    const formattedCountries = countries.map((country) => ({
      name: country.name.common,
      code: country.cca3, // Alpha-3 code like IND, USA, GBR
    }));

    // Sort alphabetically by name
    formattedCountries.sort((a, b) => a.name.localeCompare(b.name));

    res.status(200).json(formattedCountries);
  } catch (error) {
    res.status(500).json({
      message: "Error fetching countries",
      error: error.message,
    });
  }
};

